extends:
  - prettier
  - plugin:react-hooks/recommended
  - plugin:jest-dom/recommended
parser: "@babel/eslint-parser"
plugins:
  - "@babel"
  - react-hooks
  - testing-library
overrides:
  - files:
      - "**/__tests__/**/*.[jt]s?(x)"
      - "**/?(*.)+(spec|test).[jt]s?(x)"
    extends:
      - "plugin:testing-library/react"
rules:
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
